// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:5f151ee5-c159-4404-baf9-a07f615e5958",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5PkO8pXel",
    "aws_user_pools_web_client_id": "3tvfa0m9kb6uqsokkigqhht7c5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jekl72b6ffhjhmjmiet2rnveya.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
